In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('notifs_corrected.csv')

In [3]:
data

notif_id  day_of_week  hour  minute  category  \
0       568156            6    17      30         7   
1       567822            6    15      46         7   
2       567810            6    15      45         7   
3       567886            6    15      54         5   
4       568058            6    16      13         7   
5       568117            6    16      21         3   
6       470533            1    15      52         7   
7       470677            1    16      10         0   
8       470475            1    15      50         7   
9       470517            1    15      51         7   
10      470521            1    15      51         5   
11      566919            6    13      46         5   
12      470557            1    15      53         7   
13      567069            6    14       3         5   
14      565750            6    14      30         7   
15      565455            6    14      32         7   
16      567267            6    14      33         7   
17      470577            1    15      56         7   
18      567174            6    14      24         2   
19      470608            1    16       8         5   
20      565433            6    14      41         7   
21      564894            6    14      30         7   
22      470590            1    15      57         7   
23      470951            1    16      44         2   
24      470653            1    16       9         5   
25      470773            1    16      25         0   
26      470865            1    16      32         0   
27      470641            1    16      35         7   
28      470886            1    16      36         2   
29      470919            1    16      40         0   
...        ...          ...   ...     ...       ...   
6317    567565            6    16      30         7   
6318    568455            6    17       5         3   
6319    568291            6    16      42         0   
6320    568340            6    16      45         2   
6321    568365            6    16      50         7   
6322    568458            6    17       5         5   
6323    568481            6    17       7         5   
6324    568511            6    17      11         5   
6325    568520            6    17      14         5   
6326    564607            6    17      30         3   
6327    564581            6    17      30         3   
6328    568644            6    17      33         5   
6329    568658            6    17      34         5   
6330    568712            6    17      40         3   
6331    564557            6    18       0         7   
6332    566849            6    18       3         2   
6333    568893            6    18      20         7   
6334    569143            6    18      47         0   
6335    568997            6    18      31         0   
6336    569170            6    18      51         0   
6337    569448            6    19      24         7   
6338    569381            6    19      22         3   
6339    569392            6    19      20         3   
6340    569417            6    19      23         3   
6341    569410            6    19      22         3   
6342    569835            6    20      11         7   
6343    569838            6    20      17         7   
6344    549217            5    10      30         4   
6345    517302            7    13      54         4   
6346    555946            5     7      16         7   

                                                   text  
0             135 37 8 39 105 1503 1504 25 1 161 35 213  
1     72 104 1 139 93 95 137 66 537 332 139 93 495 1...  
2                           72 104 163 86 72 311 1712 1  
3     198 221 1426 538 1713 54 3 27 1714 716 38 145 ...  
4     72 104 1 139 93 95 137 66 537 332 139 93 495 1...  
5            130 21 122 169 47 66 56 178 45 179 103 206  
6     96 175 125 5 24 47 24 20 76 114 56 445 487 522...  
7     1297 972 910 1505 1427 1298 873 911 804 1505 1427  
8     96 175 125 5 24 47 24 20 76 114 56 445 487 522...  
9     96 175 12

In [37]:
a = data['text']
a = a[a.notna()]

In [39]:
lens = a.apply(lambda x:len(x.split(' ')))

In [41]:
max(lens)

67

In [43]:
test = pd.read_csv('test.csv')

In [56]:
notifs = data['notif_id'].values

array([568156, 567822, 567810, ..., 549217, 517302, 555946], dtype=int64)

In [54]:
is_in_notifs[is_in_notifs == True]

Series([], Name: notif_id, dtype: bool)

In [64]:
test_notifs = test['notif_id'].values

In [65]:
is_in_notifs = []
for item in test_notifs:
    is_in_notifs.append(item in notifs)

In [68]:
False in is_in_notifs

False

In [69]:
#pas hameye notifaye to test matneshuno darim

In [81]:
notifs.tofile('notifs.txt')

In [86]:
anotifs = np.fromfile('notifs.txt',dtype=np.int64)

In [88]:
anotifs

array([568156, 567822, 567810, ..., 549217, 517302, 555946], dtype=int64)

In [89]:
notifs

array([568156, 567822, 567810, ..., 549217, 517302, 555946], dtype=int64)

In [91]:
test_notifs.tofile('test_notifs.txt')